[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter=@altsui/shared build",
  "pnpm --filter=@altsui/api build"
]

[start]
cmd = "cd apps/api && pnpm start"



























